trigger:
 - master  
pool:
   vmImage: 'windows-latest'
steps:
  - task: NodeTool@0
    inputs:
     versionSpec: '18.x.x'
    displayName: 'Install Node.js'
  - script: |
     npm install
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'npm install'
  - script: |
     npm run build
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'npm build'
  - script: |
     npm start
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'npm start'